server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ViaJava
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=DB_VIAJAVA;encrypt=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.SQLServerDialect