package com.avanade.decolatech.viajava.strategy;

public enum EmailType {
    ACCOUNT_CONFIRMATION_EMAIL, PASSWORD_RESET_EMAIL,
    ACCOUNT_CREATED_EMAIL, RESEND_ACCOUNT_CONFIRMATION_EMAIL,
    PAYMENT_REQUEST_EMAIL, PAYMENT_CONFIRMATION_EMAIL
}
